### PR TITLE
footer change

### PR DESCRIPTION
**Pull request by TheLlamamarketer**

### CODE REVIEW

**Review by q-Sci — CHANGES_REQUESTED** [review]
Can you please optimize it for light mode too? White text on light gray background is not very easy to read. Also a horizontal scrollbar appears when you hover over a link which should be removed.

**Review by johan-t — CHANGES_REQUESTED** [review]
I agree with Simon's improvements, also please add the social media links and just show the spaced-rep tutorial even if user is not on spaced-rep page, otherwise it will result in poor user experience since they have to click again and read the text. This would be slightly annoying.

**Comment by johan-t** [comment]
Sorry for being picky, but could you also fix the merge conflicts?

**Review by q-Sci — APPROVED** [review]
Good, but we need to remember to replace some of the links once the new start page is released.

**Comment by TheLlamamarketer** [comment]
do I still need to implement something now, or is it good to be merged?

**Comment by q-Sci** [comment]
You can probably merge it. We can change things later, if there are any issues left.

**Review by johan-t — APPROVED** [review]
good work, I also like the onHoover animation very much

**Pull request merged**
