### PR TITLE
Auto complete flashcard

### PR DESCRIPTION
**Pull request by johan-t**
I created a feature with which openAi will suggest a flashcard answer to your question. I also added the feature the the premium feature list. Please try out and review my code.

To test the feature you have to open a first terminal and execute index.js inside of the server folder with node, with the second terminal you have to start the client side code with npm start

### CODE REVIEW

**Review by q-Sci — DISMISSED** [review]
There are multiple issues i have run into when testing the feature: Firstly for me no respones are generated so I cant test this feature, there were the following error messages:
```
Oops something went wrong: undefined
generateSuggestion @ flashcard-form.js:29
```
```
POST http://localhost:3001/generate-suggestion net::ERR_CONNECTION_REFUSED
```
Secondly, the app freezing issue is back when adding a folder or showing the archived ones.

**Comment by GregTCLTK** [comment]
> Secondly, the app freezing issue is back when adding a folder or showing the archived ones.

App freezing is back because https://github.com/MemoriterApp/Memoriter/pull/70/commits/aae28b71e5389d08d18dff514a32cfacdf8ef92a was pushed to main after @johan-t created his branch. Therefore, the freeze fix isn't implemented in the code on this branch yet.

**Comment by GregTCLTK** [comment]
> There are multiple issues i have run into when testing the feature: Firstly for me no respones are generated so I cant test this feature, there were the following error messages:
> 
> ```
> Oops something went wrong: undefined
> generateSuggestion @ flashcard-form.js:29
> ```
> 
> ```
> POST http://localhost:3001/generate-suggestion net::ERR_CONNECTION_REFUSED
> ```

Did you start the server in the `server/` directory?

**Comment by q-Sci** [comment]
I originally did not (no one told me you need to do it), but now I ran into an issue when starting the server. I do not know if it is some Windows or device specific error, but when starting the server nothing happens and the following error shows up in the terminal (looks like some permission related thing).

Windows PowerShell:
```
[14976:0116/182852.860:ERROR:cache_util_win.cc(20)] Unable to move the cache: Access is denied. (0x5)
[14976:0116/182852.860:ERROR:cache_util.cc(145)] Unable to move cache folder C:\Users\Simon\AppData\Roaming\Code\Cache\Cache_Data to C:\Users\Simon\AppData\Roaming\Code\Cache\old_Cache_Data_000
[14976:0116/182852.860:ERROR:disk_cache.cc(196)] Unable to create cache
```

Command Prompt:
```
[main 2023-01-17T20:59:14.767Z] update#setState idle
[main 2023-01-17T20:59:16.566Z] Starting extension host with pid 5912 (fork() took 19 ms).
[14368:0117/215917.367:ERROR:jump_list.cc(301)] Failed to append custom category 'Recent Folders' to Jump List due to system privacy settings.
[main 2023-01-17T20:59:17.393Z] updateWindowsJumpList#setJumpList unexpected result: customCategoryAccessDeniedError
[main 2023-01-17T20:59:25.645Z] Enabling inspect port on extension host with pid 5912.
```

**Comment by johan-t** [comment]
I found the error. The problem or at least one of them is with the .env file, since I can't upload the secret keys to Github you can't access them. To fix this problem I think we need to host the backend on a server along with the rest of the backend. 
So we need to wait until @GregTCLTK is finished with his branch

**Pull request closed without merging**
