### PR TITLE
cleaned up file structure

### PR DESCRIPTION
**Pull request by johan-t**
New structure

### CODE REVIEW

**Review by q-Sci — COMMENTED** [review]
Good work! The only thing missing might be some file and folder names using incorrect naming conventions.

**Comment by johan-t** [comment]
did we have a folder naming convention? Or how specifically should I fix the naming? @q-Sci

**Comment by johan-t** [comment]
I changed the naming a bit, if it is alright please merge, we can still change details later on

**Review by GregTCLTK — APPROVED** [review]

**Review by q-Sci — APPROVED** [review]
👍

**Pull request merged**
